import {
  RUNTIME_OUTPUT_CAPTURE_POLICY,
  RUNTIME_OUTPUT_TRUNCATION_MARKER,
} from "@bayma/core";

export const BUN_INSPECTION_POLICY = {
  maxDepth: 6,
  maxEntries: 100,
  maxStringCharacters: 16_384,
  maxVisitedNodes: 1_000,
  maxRenderedBytes: RUNTIME_OUTPUT_CAPTURE_POLICY.maxMessageBytes,
} as const;

export function bunInspectionPrelude(): string[] {
  return [
    `const __baymaInspectionPolicy = ${JSON.stringify(BUN_INSPECTION_POLICY)};`,
    `const __baymaBoundText = (value) => {`,
    `  const text = String(value);`,
    `  const bytes = Buffer.from(text);`,
    `  const maxBytes = __baymaInspectionPolicy.maxRenderedBytes;`,
    `  if (bytes.length <= maxBytes) return text;`,
    `  const marker = Buffer.from(${JSON.stringify(RUNTIME_OUTPUT_TRUNCATION_MARKER)});`,
    `  const payloadBytes = maxBytes - marker.length;`,
    `  const leftTarget = Math.floor(payloadBytes / 2);`,
    `  const rightTarget = bytes.length - (payloadBytes - leftTarget);`,
    `  let left = leftTarget;`,
    `  while (left > 0 && (bytes[left] & 0xc0) === 0x80) left -= 1;`,
    `  let right = rightTarget;`,
    `  while (right < bytes.length && (bytes[right] & 0xc0) === 0x80) right += 1;`,
    `  return bytes.subarray(0, left).toString("utf8") + marker.toString("utf8") + bytes.subarray(right).toString("utf8");`,
    `};`,
    `const __baymaPreviewString = (value) => {`,
    `  const limit = __baymaInspectionPolicy.maxStringCharacters;`,
    `  if (value.length <= limit) return value;`,
    `  let prefix = value.slice(0, limit);`,
    `  const last = prefix.charCodeAt(prefix.length - 1);`,
    `  if (last >= 0xd800 && last <= 0xdbff) prefix = prefix.slice(0, -1);`,
    `  return prefix + "…" + (value.length - prefix.length) + " characters omitted…";`,
    `};`,
    `const __baymaPreview = (value, depth = 0, state = { nodes: 0, seen: new WeakSet() }) => {`,
    `  if (typeof value === "string") return __baymaPreviewString(value);`,
    `  if (value === null || (typeof value !== "object" && typeof value !== "function")) return value;`,
    `  if (state.nodes >= __baymaInspectionPolicy.maxVisitedNodes) return "[inspection node limit]";`,
    `  state.nodes += 1;`,
    `  if (state.seen.has(value)) return "[Circular]";`,
    `  if (depth >= __baymaInspectionPolicy.maxDepth) return "[" + (value?.constructor?.name || typeof value) + " depth limit]";`,
    `  state.seen.add(value);`,
    `  if (value instanceof Date) return Number.isNaN(value.getTime()) ? "Invalid Date" : value.toISOString();`,
    `  if (value instanceof RegExp) return String(value);`,
    `  if (value instanceof Error) return { name: value.name, message: __baymaPreviewString(value.message), stack: __baymaPreviewString(value.stack || "") };`,
    `  if (ArrayBuffer.isView(value)) {`,
    `    const length = typeof value.length === "number" ? value.length : value.byteLength;`,
    `    const shown = Array.from(value.slice?.(0, __baymaInspectionPolicy.maxEntries) ?? []);`,
    `    if (length > shown.length) shown.push("…" + (length - shown.length) + " entries omitted…");`,
    `    return { [value.constructor?.name || "TypedArray"]: shown };`,
    `  }`,
    `  if (Array.isArray(value)) {`,
    `    const shown = [];`,
    `    const count = Math.min(value.length, __baymaInspectionPolicy.maxEntries);`,
    `    for (let index = 0; index < count; index += 1) shown.push(__baymaPreview(value[index], depth + 1, state));`,
    `    if (value.length > count) shown.push("…" + (value.length - count) + " entries omitted…");`,
    `    return shown;`,
    `  }`,
    `  if (value instanceof Map) {`,
    `    const shown = [];`,
    `    let count = 0;`,
    `    for (const [key, entry] of value) {`,
    `      if (count >= __baymaInspectionPolicy.maxEntries) break;`,
    `      shown.push([__baymaPreview(key, depth + 1, state), __baymaPreview(entry, depth + 1, state)]);`,
    `      count += 1;`,
    `    }`,
    `    if (value.size > count) shown.push(["…", value.size - count + " entries omitted"]);`,
    `    return { ["Map(" + value.size + ")"]: shown };`,
    `  }`,
    `  if (value instanceof Set) {`,
    `    const shown = [];`,
    `    let count = 0;`,
    `    for (const entry of value) {`,
    `      if (count >= __baymaInspectionPolicy.maxEntries) break;`,
    `      shown.push(__baymaPreview(entry, depth + 1, state));`,
    `      count += 1;`,
    `    }`,
    `    if (value.size > count) shown.push("…" + (value.size - count) + " entries omitted…");`,
    `    return { ["Set(" + value.size + ")"]: shown };`,
    `  }`,
    `  if (typeof value === "function") return "[Function " + (value.name || "anonymous") + "]";`,
    `  const shown = {};`,
    `  let count = 0;`,
    `  for (const key in value) {`,
    `    if (!Object.prototype.hasOwnProperty.call(value, key)) continue;`,
    `    if (count >= __baymaInspectionPolicy.maxEntries) { shown["…"] = "more properties omitted"; break; }`,
    `    const descriptor = Object.getOwnPropertyDescriptor(value, key);`,
    `    shown[key] = descriptor && "value" in descriptor ? __baymaPreview(descriptor.value, depth + 1, state) : "[Getter/Setter]";`,
    `    count += 1;`,
    `  }`,
    `  return shown;`,
    `};`,
    `const __baymaInspect = (value, rawString = false) => {`,
    `  try {`,
    `    if (rawString && typeof value === "string") return __baymaBoundText(__baymaPreviewString(value));`,
    `    return __baymaBoundText(Bun.inspect(__baymaPreview(value), { colors: false, depth: __baymaInspectionPolicy.maxDepth }));`,
    `  } catch {`,
    `    return "[Bayma could not inspect value]";`,
    `  }`,
    `};`,
    `const __baymaCaughtErrorText = (value) => {`,
    `  try {`,
    `    if (value !== null && (typeof value === "object" || typeof value === "function")) {`,
    `      const message = Reflect.get(value, "message");`,
    `      const stack = Reflect.get(value, "stack");`,
    `      const name = Reflect.get(value, "name");`,
    `      if (typeof message === "string") {`,
    `        if (typeof stack === "string" && stack) return __baymaBoundText(stack);`,
    `        return __baymaBoundText((typeof name === "string" && name ? name + ": " : "") + message);`,
    `      }`,
    `    }`,
    `  } catch {`,
    `  }`,
    `  return __baymaInspect(value);`,
    `};`,
  ];
}
